USE  customer_analysis
#SELECT * FROM customers;
# Business Insight Questions
#1 which category generates the highest revenue
SELECT 
    Category,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY Category
ORDER BY total_revenue DESC
-- Insight:
-- Clothing is the top revenue-generating category,
-- suggesting it is the most profitable product segment.

# 2 Are discounts increasing the purchase value?
SElECT
	discount_applied,
    ROUND(AVG(purchase_amount)) AS avg_purchase,
    ROUND(SUM(purchase_amount)) AS total_purchase
    FROM customers
    GROUP BY discount_applied;
-- Insight:
-- Customers who received discounts had a higher average purchase value
-- (163) compared to customers without discounts (131),
-- indicating that discounts encourage customers to spend more per purchase.

-- However, the total revenue generated from discounted purchases
-- (321,960) was slightly lower than non-discounted purchases (328,615).

-- This suggests that while discounts improve customer spending behavior,
-- they may not significantly increase overall business revenue
-- and could potentially impact profitability.

# Recommendation
#The company should optimize discount strategies to improve profitability while maintaining higher customer spending.


#3 Total revenue generated by male and femal category
SELECT 
	gender,
    round(SUM(purchase_amount))AS total_revenue
    FROM customers
    GROUP BY gender;
    
-- Insight:
-- Male customers generated higher total revenue compared to female customers,
-- indicating stronger overall purchasing contribution from the male segment.

-- Recommendation:
-- The business can further analyze male customer preferences and purchasing behavior
-- to create targeted marketing campaigns and personalized product strategies
-- while also exploring opportunities to improve engagement among female customers.



#4 Which customer used a discount but still spent more than the average purchase amount ? 
SELECT
	customer_id
    purchase_amount,
    discount_applied
FROM customers
WHERE discount_applied = 'yes'
AND purchase_amount > (
	SELECT AVG(purchase_amount)
    FROM customers
    );
    
-- Insight:
-- Several customers who received discounts still spent above the overall average purchase amount,
-- indicating that discounts may effectively encourage high-value purchases.

-- Recommendation:
-- The business can target similar high-spending customers with personalized discount campaigns
-- to maximize customer retention and revenue generation.

#5Which are the top/bottom 5 products with the highest average review rating.

SELECT
	item_purchased,
    AVG(review_rating) as avg_review
    FROM customers
GROUP BY item_purchased
ORDER BY avg_review
LIMIT 5;

-- Insight:
-- Laptop and Bag received comparatively higher average review ratings,
-- indicating better customer satisfaction for these products.

-- Phone received the lowest average rating among the listed products,
-- suggesting possible issues related to quality, pricing, or customer expectations.

-- Recommendation:
-- The business should further investigate customer feedback and reviews for Phone products
-- to identify pain points and improve customer satisfaction.

-- Products with higher ratings such as Laptop and Bag can be promoted more aggressively
-- in marketing campaigns to leverage positive customer perception.

#6Average purchase: Standard vs Express shipping
SELECT
	shipping_type,
    AVG(purchase_amount) as avg_purchase
    FROM customers
    GROUP BY shipping_type;

-- Insight:
-- Customers choosing Express and Standard shipping showed significantly higher
-- average purchase amounts compared to other shipping methods.

-- Shipping methods such as Free Shipping, Store Pickup, and Next Day Air
-- had relatively lower average purchase values.

-- This suggests that customers opting for premium or paid shipping methods
-- are likely making higher-value purchases.

-- Recommendation:
-- The business can offer personalized premium shipping incentives
-- for high-value customers to enhance customer experience and revenue generation.

-- The company can also analyze why lower-cost shipping methods
-- are associated with smaller purchase amounts and explore upselling opportunities.

-- 7 Do subscribed customers spend more ? Compare average spend and total revenue between
-- subscribers and non-subscribers.

SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY subscription_status;

-- Insight:
-- Subscribed customers spend significantly more on average (198.65)
-- compared to non-subscribers (122.31),
-- indicating stronger purchasing behavior among subscribers.

-- However, non-subscribers generated higher total revenue overall,
-- likely due to a larger number of non-subscriber customers in the dataset.

-- Recommendation:
-- The business should focus on converting more non-subscribers into subscribers,
-- as subscribers demonstrate higher spending potential per purchase.

-- Personalized membership benefits, loyalty programs, and exclusive offers
-- can help improve subscription adoption and long-term customer value.

#8. Top 5 products with highest discount usage %
SELECT 
    item_purchased,
    
    COUNT(
        CASE 
            WHEN discount_applied = 'Yes' THEN 1 
        END
    ) * 100.0 / COUNT(*) AS discount_usage_percentage
FROM customers
GROUP BY item_purchased
ORDER BY discount_usage_percentage DESC
LIMIT 5;

-- Insight:
-- Laptop and Phone showed the highest discount usage percentages,
-- indicating customers are more likely to purchase these products when discounts are offered.

-- Recommendation:
-- The business can use targeted discount campaigns for high-demand products
-- to further improve sales and customer engagement.

# 9 egment customer into new, returning and loyal based on their total number of previous purchase,
-- and show the count of each segment.

SELECT 
    CASE 
        WHEN previous_purchases <= 10 THEN 'New'
        WHEN previous_purchases <= 20 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customers
GROUP BY customer_segment;

-- Insight:
-- Loyal customers form the largest customer segment,
-- indicating strong repeat purchasing behavior and customer retention.

-- Recommendation:
-- The business should continue rewarding loyal customers through loyalty programs
-- while encouraging new and returning customers to purchase more frequently.

#10 Are customers who are repeat buyers (more than 5 previous purchases) 
SELECT 
    subscription_status,
    COUNT(*) AS customer_count
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

#11 what is the revenue contribution of each age group?
SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN 'Young Adults'
        WHEN age BETWEEN 26 AND 40 THEN 'Adults'
        ELSE 'Seniors'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group;

-- Insight:
-- Adult customers contributed the highest share of total revenue,
-- indicating they are the most valuable customer segment.

-- Recommendation:
-- The business should focus targeted marketing and personalized offers
-- on high-performing age groups to maximize revenue growth.